name: 'kenya_trends'
version: '1.0.0'
config-version: 2

profile: 'kenya_trends'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  kenya_trends:
    staging:
      +materialized: view
    marts:
      +materialized: view
