name: 'kenya_trends_google'
version: '1.0.0'
config-version: 2

profile: 'kenya_trends_google'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  kenya_trends_google:
    +materialized: view
