kenya_trends:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: data-storage-485106
      dataset: google
      keyfile: /tmp/keyfile.json
      location: US
      timeout_seconds: 300
      threads: 1
