name: 'youtube_trending_now'
version: '1.0.0'
config-version: 2

profile: 'youtube_trending_now'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  youtube_trending_now:
    +materialized: view
